### PR TITLE
Parametric umap

### PR DESCRIPTION
**Pull request by timsainb**
This includes the main parametric umap code as umap.parametric_umap, a test_ file, and rst documentation, added to the index. 
I'm not 100% on how best to test that this will integrate properly with UMAPs current documentation and CI, but they worked locally on sphinx and pytest.
I added tensorflow > 2.0 as a requirement using the same notation as umap.plot in setup.py as well.

### CODE REVIEW

**Comment by lmcinnes** [comment]
I am definitely super excited about getting this included and working. It is going to take a me a little while to go through everything here though, so please be patient with me on this PR.

**Comment by timsainb** [comment]
Awesome. In the meantime I can  try to make CI happy. I am right now trying to fix the import errors.

It looks like there in a script in ci_scripts/install.sh where I should add `pip install tensorflow`
I also see a doc/doc_requirements.txt where datashader, etc are installed. Should I add a line there as well?

**Comment by lmcinnes** [comment]
Errors seem to all be due to my in development stuff on this branch.

**Comment by lmcinnes** [comment]
Thanks for this -- it is a major addition. I particularly appreciate the effort that went into adding extra notebooks and documentation, as well as tests for the new code. It makes a huge difference in supporting and maintaining this.

**Pull request merged**
