### PR TITLE
Densmap supervised (issue 609)

### PR DESCRIPTION
**Pull request by rxjx**

### CODE REVIEW

**Comment by lmcinnes** [comment]
Could you run it supervised on Fashion-MNIST and post the resulting plot? I just want to be sure it "mostly works" in reasonable cases.

**Comment by rxjx** [comment]
Yeah, I think I can do it over the weekend.

**Comment by rxjx** [comment]
image

**Comment by lmcinnes** [comment]
Looks good! I was worried there might be enough weird interactions to make it go screwy, but it seems good enough for now. Thanks for taking the time and trouble to look into this. The test is also greatly appreciated.

**Comment by rxjx** [comment]
No problem at all. Thank you for UMAP and all the work you've put into it.

**Pull request merged**
