### PR TITLE
demo umap docs build with sktda docs

### PR DESCRIPTION
**Pull request by sauln**
This conf file demonstrates how umap docs page would integrate the sktda docs system.

You'll see it massively simplifies the conf.py, putting the logic inside the [sktda_docs_config package](https://pypi.org/project/sktda-docs-config/) and on [github](https://github.com/scikit-tda/sktda-docs-config).

To setup and see how it runs, install `sktda-docs-config` and `sphinx_gallery` into an environment with umap. Then run `make html` in the `doc` directory. You can view the results by opening `_build/html/index.html` in your browser.

This does not include the ability to manage versions in the docs, unfortunately, but it looks like UMAP is not currently using that feature of readthedocs.

Let me know what you think and we can figure out the next steps for integration.

### CODE REVIEW

**Comment by lmcinnes** [comment]
Thanks for this -- I'll try to look through it shortly when I have  a little more time.

**Comment by lmcinnes** [comment]
Apparently time is at a premium. Perhaps we can discuss this at SciPy this year?

**Comment by lmcinnes** [comment]
Sorry -- I just never quite got to this :-(

**Comment by sauln** [comment]
Totally understand.  The docs are fine as they are. I've actually been thinking of converting the rest of the scikit-tda docs to readthedocs so management is a bit easier.

**Pull request closed without merging**
