### PR TITLE
WIP: Supervised example

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by lmcinnes** [comment]
Thanks! Always nice to have extra examples. Did you want to link to or reference this example in the documentation? It would certainly be welcome, but is definitely not necessary. If not then just let me know and I'll merge this as is.

**Comment by bkmgit** [comment]
Have added a draft in the documentation. Are svg figures ok? These are better for screen readers when they are not too large.

**Comment by lmcinnes** [comment]
Looks good to me. Thanks for submitting this, it is greatly appreciated.

**Comment by bkmgit** [comment]
Added images in #700

**Pull request merged**
