### PR TITLE
check before reshaping labels to 2D

### PR DESCRIPTION
**Pull request by ajtritt**
## Problem
When trying to do supervised embedding, using multi-dimension continuous variables, the error below was raised. The current code was assuming labels were single dimension, and always adding a new axis. 

## Solution
Check before reshaping labels

### Error

```
Traceback (most recent call last):
  File "$COND_ENV/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "$COND_ENV/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ajtritt/projects/exabiome/exabiome.git/src/exabiome/response/umap.py", line 108, in <module>
    n_neighbors=args.n_neighbors)
  File "/Users/ajtritt/projects/exabiome/exabiome.git/src/exabiome/response/umap.py", line 40, in run_umap
    emb = umap.fit_transform(dist, y=labels)
  File "$PATH_TO_UMAP/umap.git/umap/umap_.py", line 1598, in fit_transform
    self.fit(X, y)
  File "$PATH_TO_UMAP/umap.git/umap/umap_.py", line 1505, in fit
    **self._target_metric_kwds
  File "$COND_ENV/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 1749, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "$COND_ENV/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 1348, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "$COND_ENV/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 262, in euclidean_distances
    X, Y = check_pairwise_arrays(X, Y)
  File "$COND_ENV/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 137, in check_pairwise_arrays
    estimator=estimator)
  File "$COND_ENV/lib/python3.7/site-packages/sklearn/utils/validation.py", line 558, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2.
```

### CODE REVIEW

**Comment by lmcinnes** [comment]
Same issue of black for formatting in this case. Otherwise this is a great addition. Thank you!

**Comment by ajtritt** [comment]
These constraints are infeasible... black is okay with lines up to 88 characters, but pep8 caps it at 79. I can run `black -l 79`, but that will hit everything.

**Comment by ajtritt** [comment]
#378 should fix this

**Comment by lmcinnes** [comment]
Thanks for the pep8 fix -- I agree. I prefer black's 88 char limit. It is more reasonable for many cases.

**Comment by lmcinnes** [comment]
I'm not sure what the black issues are here -- but the changes are simple enough so I'll just merge this and sort out the formatting later. Thanks again for the fix!

**Pull request merged**
