### PR TITLE
First implementation to Fix Issue #590

### PR DESCRIPTION
**Pull request by leriomaggio**
Ok @lmcinnes so, following on your comment on the ugliness of the first workaround implementation (and I totally shared the feeling), here is a different attempt to fix the function and to also get rid of code duplications with a more compact implementation covering the two cases.

**Issue**: The issue was indeed related to the `result` array being allocated differently (as in different shapes) within the two alternative `if` branches - this upsets `numba` for some reason. Still not quite sure why.
Therefore, another quick _workaround_ implementation is provided, and tested as `pytest.fixture`
(please see [here](https://github.com/lmcinnes/umap/blob/abdfddb650d28dbae74be2202c370fde0ab67fee/umap/tests/test_chunked_parallel_spatial_metric.py#L7))

Specifically, a new _dedicated_ test module has been created to verify the **proposed** [compact implementation](https://github.com/lmcinnes/umap/blob/abdfddb650d28dbae74be2202c370fde0ab67fee/umap/distances.py#L1252) and the original workaround.

Of course, it goes without saying that both implementations allow all tests in `test_umap_metrics` to **PASS**.

Please see below the description of the commit:  

>This commit includes a new implementation for the `chunked_parallel_spatial_metric` in `distances` to fix issue #590 causing Python 3.8 to fail tests in the case when `X` and `Y` parameters are passed.
>
>In more details, this new implementation addresses the issue and also provides a more compact version to avoid code duplications on the two branches (i.e. `Y is|is not None`).
>
>In order to tests the two implementations, a special fixture/decorator is created to compare calculations with a quick-fix implementation of the previous original `chunked_parallel_special_metric` as implemented by Leland.

Feel free to send feedback on the compact implementation: personally I tried to replicate the same logic in your initial idea. 

However, I am not necessarily convinced that adding those `if clauses` for the `symmetrical` cases is indeed more performant than doing the iteration loop (in parallel) in all locations, anyway. 
It is indeed true that in the case of very big matrices, lots of computation can be saved - at the price of `if clauses` which are notoriously costly. 

I would love to hear your comments on this! Thank you :)

### CODE REVIEW

**Comment by lmcinnes** [comment]
I like what you manage to do the clean things up from the first fix you posted to the issue! It looks a lot cleaner now. I'll have to do some benchmarking and see how performance compares because, as you note, the if statements now introduce some extra overhead.

**Comment by lmcinnes** [comment]
So the good news is that it works; the bad news is that, at least in my quick benchmarking, it is very slow. I suspect the added if statements create a lot of overhead in what are tight inner loops, so the whole thing slows down a lot. I'll try and see if I can come up with an alternative formulation that still works, but runs as fast as the old version.

**Comment by leriomaggio** [comment]
Great @lmcinnes thanks a lot for the feedback and the quick benchmarking - I was indeed too curious to see whether our initial guess about the `if-clause` were indeed correct. 

So I setup a quick benchmark tests (using `pytest-benchmark` - first time, lots of fun indeed!!) and run it on two alternative implementations (I simply tried the same getting rid of the if clauses). 

I could indeed try the "ugly" workaround too for comparison 👍 
I also pushed the benchmark report - thought it was the quickest to share it, we will remove it before merging.

Here is the link to the [benchmark report](https://github.com/lmcinnes/umap/blob/quickfix_chunked_parallel_special_metric/chunked_parallel_benchmark_report_valerio_macbook_CPU.txt)

**Note**: I've done a bit of editing to testing function names to allow for an easier-to-read report!
Quick legend: `test_with_IF_` refers to the implementation with the IF clause checks ([implementation](https://github.com/lmcinnes/umap/blob/d4b54b73ec57267fecad07cc513df94f4063f848/umap/tests/test_chunked_parallel_spatial_metric.py#L65)); 
`test_FULL_it_` refers to the alternative implementation with no control, and full iterations ([implementation](https://github.com/lmcinnes/umap/blob/d4b54b73ec57267fecad07cc513df94f4063f848/umap/tests/test_chunked_parallel_spatial_metric.py#L99)).
Suffices `_x_only` or `x_y` are self-explanatory and refers to the function called with either `X` and `X, Y` respectively.

Results are indeed interesting, now I'm intrigued how the workaround behaves. 
At a very first glance, it looks that we were right!

Looking forward to receiving your impressions too! 🙌 
Thanks a lot for testing on Py3.9 & Numba as well!

**Comment by leriomaggio** [comment]
Ah btw, "RE: `pytest-benchmark`

Forgot to say: the great thing about that plugin was that I was able to specify a "group" name for tests so it automatically grouped runs for comparison. It seems very well done, indeed.

**Comment by lmcinnes** [comment]
I wouldn't mind the "ugly workaround" for comparison, although your new alternative approach to remove the if looks pretty good.

The pytest-benchmark looks pretty useful! I wonder if we should have some benchmark reports produced for a few standard datasets so we can check for performance regressions. It would probably be a matter of setting that up as a separate run on azure pipelines. Certainly something for the future.

**Comment by leriomaggio** [comment]
Brilliant! 

The "ugly workaround" is running - it _should_ take less time than the other, and I should be able to post results soon! 🙌 

RE: Performance Regression tests: ➕ 1 
I personally think that this is a wonderful idea! Should also allow to keep track of performance through the different `numba` versions in the backend.

**Comment by leriomaggio** [comment]
Report pushed: the two implementations are indeed pretty close! (the ugly is still winning slightly)
In this benchmark I also changed the input data size, ranging from a `matrix [100x100]` up to `[1000x1000]`.

They ran on my laptop (with no GPU acceleration). Performance are not that bad, after all :)
Intrigued to test on a GPU - will try that later, if I have time.

**Comment by lmcinnes** [comment]
The two options look pretty much comparable, so I would suggest you go with whichever you prefer.

**Comment by leriomaggio** [comment]
Brilliant, thanks! So I already updated `distances.py` with the new implementation in my last commit. 
The last thing I would like to discuss with you is what to do with the test and the reports in the repository, before merging into `main`.

I shall assume I can get rid of performance reports, and that's fair.
What about performance testings? 

My suggestion right now would be to keep them in the test suite, but skip them - similarly to what we do now when skipping tests for unmet dependencies (e.g. `Tensorflow`).

So, if no `BENCHMARK` variable is set in `os.environ`, we are going to skip those tests - so that we can enable that variable in the future if we aim at including performance regression testing. 

Does this make any sense?

Thanks, Valerio

**Comment by lmcinnes** [comment]
Sounds good to me!

**Comment by leriomaggio** [comment]
> Sounds good to me!

Brilliant, thanks! I've just pushed those changes, and a bit of refactoring - polishing the tests a bit. 
It should be ready for MERGE :)

**Pull request merged**
